### ISSUE TITLE
Broken Queries Lock Up the UI

### ISSUE THREAD

**Issue by royalaid** [wilkerlucio/pathom-viz#25]
Submitting invalid queries, i.e. `[{[:curriculum/uuid <snip>]}]`, causes the UI to lock up

**Comment by wilkerlucio** [comment]
Hello, I just tried to reproduce, but I can't get the UI to freeze, can you give more details?

**Comment by royalaid** [comment]
I will try to get a reproduction repo up next week

**Comment by royalaid** [comment]
Apologies this took so long to investigate. You're correct that the UI doesn't lock with broken queries. It is just that the ability to run a query after attempting to submit a broken query like above, the "Run Query" toggles to a locked state. Another way to if you start a client and connect it to pathom viz, kill that client, then submit a query. Both of these states I have corrected by just issuing a hard refresh of the Electron window. A cancel active query button would also be another potential fix.

**Comment by wilkerlucio** [comment]
Hello @royalaid , I tried to reproduce it again, but I can't get the UI to lock up, here is a Loom video of me trying to: https://www.loom.com/share/6d882db17c2b4bf9a0b5bbd9c52cd566

If you have a way to reproduce please let me know, closing it for now.
