### ISSUE TITLE
Pathom mode - auto complete union joins

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom-viz#3]

**Comment by patrickcmserrano** [comment]
Do you have any ideas about how to begin with this?

**Comment by wilkerlucio** [comment]
Hello @patrickcmserrano, to make this happen we need to:

1. Make the [Pathom Mode](https://github.com/wilkerlucio/pathom-viz/blob/master/src/core/com/wsscode/pathom/viz/pathom-mode.js) understand EQL unions. The Pathom Mode is a codemirror mode extension, so you can look up [their docs](https://codemirror.net/2/doc/manual.html#modeapi).
2. Extend on the [completions helpers](https://github.com/wilkerlucio/pathom-viz/blob/045f536cde68fa8d8ce4c02971f6f1023f744561/src/core/com/wsscode/pathom/viz/codemirror.cljs#L130-L222) to support unions.

That said, I just open issue #36, with the idea to start all this over, making it for Codemirror 6.

What you think about writing this new mode in CM6?

**Comment by wilkerlucio** [comment]
I'll close issues related to the old codemirror, all work related to it should now go into the CM6 version, track it at #36 .
