### ISSUE TITLE
Problems with automatic re-formatting of EQL.

### ISSUE THREAD

**Issue by wardle** [wilkerlucio/pathom-viz#39]
Hi. When I paste EQL from my editor, or try to edit, it gets re-formatted automatically creating invalid EQL.

https://user-images.githubusercontent.com/286951/117550877-a6ebe000-b03a-11eb-89d3-067efc23509a.mov

This didn't used to be an issue, as far as I am aware - so I may be doing something wrong!

**Comment by wilkerlucio** [comment]
The editor uses parinfer, so a wrong indent will usually mean a wrong syntax.

When I paste from the root I usually have no problem, but sometimes pasting in the middle of a query can get in the wrong states. In those cases, just go to the part where the bad starts (second line in your case) and start pulling it down, the parinfer will eventually just balance everything (move disregarding how the separators look like, just indentation level matters).

I like to have those fixed when the editor gets replaced with CM6, but it's low on my priorities. But happy to assist if anybody wants to take over this part.

**Comment by wilkerlucio** [comment]
Closing for now, if you think there is a bug please re-open it.

**Comment by wardle** [comment]
Sorry Wilker - you’re absolutely right - I had some screwy indenting from a text file. Thank you for looking at this.
