### ISSUE TITLE
Viz's history appears to reach a point where it stops appending

### ISSUE THREAD

**Issue by royalaid** [wilkerlucio/pathom-viz#49]
After a certain number of entries in pathom-viz's history appears to just overwrite the top most entry in the list instead of push/poping like one would expect, i.e. LIFO.
Gif of the problem: https://gfycat.com/bewitchedchiefhoneybee

**Comment by wilkerlucio** [comment]
Fixed 18d55ecff00b3c39112dacb73acc3f14a06fb6da
